plugins {
    id 'java'
    id 'signing'
    id 'com.github.johnrengelman.shadow' version '8.1.1' // for fat JAR (like maven-assembly-plugin)
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven {
        name = 'sonatypeSnapshots'
        url = uri('https://oss.sonatype.org/content/repositories/snapshots/')
    }
}

apply plugin: 'java'

group = 'com.esotericsoftware'
version = '5.6.3-SNAPSHOT'
description = 'Fast, efficient Java serialization. This is the parent build.'
java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8

ext {
    junitVersion = '5.13.1'
    kotlinVersion = '2.1.21'
}

sourceSets {
    main {
        java { srcDirs = ['src'] }
    }
    test {
        java { srcDirs = ['test'] }
    }
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation 'org.apache.commons:commons-lang3:3.17.0'
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    
    implementation 'com.esotericsoftware:reflectasm:1.11.9'
    implementation 'com.esotericsoftware:minlog:1.3.1'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

description = 'Fast, efficient Java serialization. This is the main Kryo artifact.'

    
java {
    withJavadocJar()
    withSourcesJar()
}

jar {
    manifest {
        attributes(
            'Automatic-Module-Name': 'com.esotericsoftware.kryo'
        )
    }
}

tasks.named('jar') {
    archiveClassifier.set('')
}

tasks.register('assembly', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    archiveClassifier.set('all')
    from(sourceSets.main.output)
    configurations = [project.configurations.runtimeClasspath]
    manifest {
        attributes 'Main-Class': 'com.esotericsoftware.kryo.Kryo' // example
    }
}
artifacts {
    archives tasks.named('assembly').get()
}
